# Feinabstimmung {.unnumbered}

## Definitionen und Erklärungen

- Führendes und folgendes Bootsende
- Führender und folgender Paddler
- Aktive Paddelseite

## Allgemeingültige Dinge

### Initiation

- Der Bugpaddler entscheidet die Drehrichtung.
- Initiation findet gleichzeitig statt.
- Alle Manöver vorwärts zur Onside und rückwärts zur Offside können mit diagonalen Ziehschlägen eingeleitet werden.
- Alle Manöver vorwärts zur Offside und rückwärts zur Onside können mit einem kurzen Bogenschlag (beim führenden Paddler) und überkorrigierten J-Schlag (beim folgenden Paddler) eingeleitet werden. 
- Side slips haben keine Einleitung und können daran erkannt werden.
- Aus Side slips kann man aber auch wunderbar direkt in Manöver übergehen. Wann in welche Richtung weggedreht wird, ist dann ein wenig Gefühlssache, die Kantung sollte in dem Fall dann aber nicht gewechselt werden, sondern nur verstärkt werden, sonst entsteht zu viel Unruhe.


### Placement

- führender Paddler
  - Die aktive Paddelseite bleibt während des Placements die gleiche
  - Der Winkel kann zwischen neutraler Haltung und kompletter Bremsung variiert werden.
- folgender Paddler
  - Die aktive Paddelseite ist variabel. Je nach gewünschtem Manöververlauf kann die aktive Seite mehrfach wechseln. 
  - Beeinflusst damit entscheidend den Charakter des Manövers:
    - Kann das Ausbrechen des folgenden Bootsendes verhinden und das Boot auf seiner Kurvenfahrt stabilisieren (mit einem Christie nicht möglich). Das Momentum bleibt entlang der Längsachse des Bootes erhalten.
    - Kann das Ausbrechen des folgenden Bootsendes zulassen oder unterstützen und damit eine Drehung des Bootes begünstigen. Aus einem Vorwärtsmanöver kann die Fahrt dann rückwärts, aber in gleicher Fahrtrichtung, forgesetzt werden oder umgekehrt. Das Moment bleibt in der ursprünglichen Bewegungsrichtung erhalten. 


### Kantung -- rein

- Der Bugpaddler gibt die Richtung der Kantung vor. Heckpaddler folgt leicht zeitversetzt mit der Kantung (insbesondere bei Cross Placement mit Offside Kante für den Bugpaddler wichtig).

### Conclusion

- Der Paddler mit dem weiteren Weg zur Conclusion bestimmt den Beginn, es sei denn er kann vom anderen Paddler nicht gesehen werden.
- Bei Rückwärtsmanövern gibt im Idealfall der Heckpaddler das Timing vor, weil er die Bootsdrehung besser beurteilen kann. Das ist allerdings nicht in allen Manövern gut machbar, weil der Bugpaddler nicht immer ausreichende Sicht nach hinten hat.
- Eine versetzte Conclusion ergibt Sinn, wenn der Weg von der Conclusion zum nächsten Schlag für beide unterschiedlich lang ist, der nächste Schlag aber zeitgleich gemacht werden soll.
- Eine versetzte Conclusion ergibt häufig einen runderen Ablauf, aber eine parallel ausgeführte Conclusion funktioniert ebenfalls.
- Cross Axle und Cross Post haben eine versetzte Conclusion
  - Der Bugpaddler beginnt die Conclusion
  - Ausnahme: Macht der Heckpaddler ein Cross-Placement beginnt er die Conclusion (weiterer Weg, s.o.) (Cross Forward schließt sich an, s.u. Weiterfahrt).
- Stern Cross Axle und Stern Cross Post haben eine versetzte Conclusion.
  - Der Heckpaddler beginnt die Conclusion (kann vom Bugpaddler halbwegs gesehen werden)
  - Ausnahme: Macht der Bugpaddler ein Cross Placement, wird die Conclusion parallel ausgeführt. Ein Cross Rückwärtsschlag ist wenig praxistauglich. Damit haben beide Paddler einen langen Weg zum nächsten Catch und die parallele Conclusion bietet sich an.


### Kantung -- raus

- Timing der Kantung 
  - beide Paddler (fast) zeitgleich
  - Axle/Post beim nächsten Catch
  - Wedge/Tangent Weg zum Vorwärtsschlag
- Bei Cross Manövern beim Rübergehen des Bugpaddlers die Kantung rausnehmen 
  - außer Cross Forward mit Kantung zur Onside
    - Cross Post + Cross Tangent: Catch des Cross Forward Strokes
    - Cross Axle + Cross Wedge: beim Rübergehen

### Weiterfahrt

- Wenn beide Paddler ein Cross-Placement machen, ist es günstig die Vorwärtsweiterfahrt mit Cross Forwards zu beginnen. (Rückwärts gilt dies nicht, weil ein Cross Rückwärtsschlag unbequem ist.)
- Die Länge der Manöver ist Cross und Nicht-Cross meist gleich.
- Ggf. beim ersten Vorwärtsschlag nach Manöver auch im Bug die Drehung etwas korrigieren.


<!-- - Cross-Placement im Bug: Im Heck kann die Conclusion verzögert gemacht werden, um dem Bug-Paddler Zeit zu geben, das Paddel wieder auf die Onside zu bringen (wenn kein Cross Vorwärtsschlag anschließt). -->

## Nonverbale Kommunikation

<!-- - Das Einleiten der Kantung kann man von hinten teilweise schon an den Füßen des Bug-Paddlers erkennen. Alle Körperbewegungen beobachten. Wahrscheinlich stark abhängig vom jeweiligen Paddler.  -->
<!-- - Einleitungsschläge (damit der Heckpaddler es sehen kann) -->
<!--   - Onside Drehung: 45° Ziehschlag -->
<!--   - Offside Drehung: Bugdrückschlag/kurzer Bugbogenschlag (so 30° oder so) -->
<!--   - Stern Onside Drehung: überkorrigierter Rückwärtsschlag (nicht compound!) -->
<!--   - Stern Offside Drehung: rückwärts 45° Ziehschlag -->
<!--   - Auch Rückwärtsmanöver leitet am besten der Bug-Paddler ein, weil der Heck-Paddler dann folgen kann.  -->
- Vor einem Cross-Placement im Heck nur einen sehr kurzen Vorwärtsschlag machen und zügig mit dem Paddel das Boot kreuzen, damit der Bugpaddler eine Chance hat das Placement zu erkennen. Paddel können dann synchron eingesetzt werden.
<!-- - Sideslips erkennt man an Placement ohne Initiation -->

<!-- - wenn wir beide ein Cross Placement machen, folgt direkt ein Cross Forward stroke (wenn es vorwärts weiter geht), Timing des Kantung rausnehmens dabei -->
<!--   - Cross Post + Cross Tangent: Catch -->
<!--   - Cross Axle + Cross Wedge: rübergehen -->
- wenn vorne Paddel + Kantung auf einer Seite sind, kann man von vorne den Heckpaddler nicht sehen, wenn er das Placement auf der anderen Seite hat
  - für Stern-Manöver bedeutet das, dass der Bugpaddler in dem Fall die Conclusion beginnen sollte

### Fragen, um sich heranzuarbeiten

- Fahrtrichtung
- Einleitung 
  - vorne initiiert
  - hinten wahrgenommen und aufgenommen: woran erkennt man das?
    - Paddelhaltung
    - Füße
    - Hüfte
- Weg zum Placement
- Kante
  - vorne festgelegt
  - hinten aufgenommen
    - woran erkennt man das?
      - Sitzposition
      - Füße
      - Körperspannung
    - ggf. sehr frühzeitig zu sehen
- Placement
  - Placement folgender Paddler: 2,5 Möglichkeiten
    - Neutral Slice und Cross Neutral Slice gehen immer
    - Christie, bzw. Cross Christie funktioniert bei Manövern, die zur Kurvenrichtung gekantet werden
  - gleichzeitiges Eintauchen der Paddel, wenn mindestens einer Cross geht
    - bei welchen Manövern passt das?
    - Wie wird das in den Übergang zwischen Initiation und Placement für den anderen Paddler gut eingebaut?
- Conclusion
  - den Zeitpunkt des Beginns entscheidet meist der führende Paddler
    - Bei welchen Manövern gilt das nicht? (z.B. weil der folgende Paddler den führenden nicht richtig sehen kann)
  - Timing der Conclusions beider Paddler zueinander
- Bewegung zum nächsten Catch
  - Wann genau wird die Kantung rausgenommen?
  - in welche Richtung geht es weiter?
  - wer braucht wie lange?
    - Wo endet die Conclusion? Wo geht es weiter?
    - Muss einer über das Boot?
- nächster Catch
  - Timing: wann genau?
    - gibt der Bugpaddler vor, weil der Heckpaddler reagieren kann

## Paddeln zu Takt/Musik

- Tempo um 80 geht ganz gut
- Die Länge der Initiation ist je nach Manöver sehr unterschiedlich und damit nicht immer genau einen Takt lang. 
- Rückwärts compound: far back auf 1, normaler Catch zwischen 2 und 3. So bleibt dem Bugpaddler genug Zeit für eine Korrektur.
- Alle Längen dürften stark abhängig sein von der Bootsform und der Trimmung

### Musikalische Manöverlängen

die folgende Liste gilt für

- Rieke und Marius in Elmo
- ein gutes Tempo ist für uns etwa 80 bis 95
  - mögliche Musik: Loreena McKennitt - La Serenissima (87)
  - Catch jeweils auf der 1
- die Zahlen beschreiben die Taktanzahl für Initiation, Placement, Conclusion (einige Manöver können schneller gehen, wenn man flott reinfährt, das ist die letzte Spalte)

+---------------------+----------+-------------------+
| Manöver             | Takte    | flotte Ausführung |
+=====================+==========+===================+
| Axle                | 1 4 2    |                   |
+---------------------+----------+-------------------+
| Post                | 1 4 2    |                   |
+---------------------+----------+-------------------+
| Wedge               | 1 3 2    |                   |
+---------------------+----------+-------------------+
| Tangent             | 1 3 2    |                   |
+---------------------+----------+-------------------+
| Stern Axle          | 1 4 2    | 1 3 2             |
+---------------------+----------+-------------------+
| Stern Post          | 1 4 2    | 1 3 2             |
+---------------------+----------+-------------------+
| Stern Wedge         | 1 3 2    |                   |
+---------------------+----------+-------------------+
| Stern Tangent       | 1 3 2    |                   |
+---------------------+----------+-------------------+
| Stern Axle          | 1 3 1    |                   |
+---------------------+----------+-------------------+
| Stern Post          | 1 3 1    |                   |
+---------------------+----------+-------------------+
| Stern Wedge         | 1 3 1    |                   |
+---------------------+----------+-------------------+
| Stern Tangent       | 1 3 1    |                   |
+---------------------+----------+-------------------+
| Stern Cross Axle    | 1 4 1    | 1 3 1             |
+---------------------+----------+-------------------+
| Stern Cross Post    | 1 4 1    |                   |
+---------------------+----------+-------------------+
| Stern Cross Wedge   | 1 3 1    |                   |
+---------------------+----------+-------------------+
| Stern Cross Tangent | 1 3 1    |                   |
+---------------------+----------+-------------------+
| Sideslips           | variabel |                   |
+---------------------+----------+-------------------+
| Gimbal              | variabel |                   |
+---------------------+----------+-------------------+

- meistens sind nicht Cross und Cross Manöver gleich
  - man muss sich überlegen, wo das Rübernehmen des Paddels untergebracht wird
- im 3. Quadranten sind alle Manöver gleich
- Conclusion für Cross Axle + Cross Post
  - vorne: 1. Takt = loaded slice, 2. Takt = rübernehmen
  - hinten: bis zum 2. Takt warten


### Fragen, um sich heranzuarbeiten

- Was ist eine komfortable Paddelfrequenz? (ggf. mit Metronom testen)
- Wie lang sind die Manöver (in Takten) mit dem Team und Boot?
- je nach Trim verhalten sich vorwärts und rückwärts Manöver sehr unterschiedlich

## Sonstiges

- beim ersten Vorwärtsschlag nach Manöver auch vorne Drehung etwas korrigieren
- cross Vorwärtsschläge nach Cross Manöver (passt aber nicht immer flüssig)
