Freestyle im Tandem bietet sehr viel mehr Freiheiten und Variationsmöglichkeiten als im Solo. Dieses Dokument ist als Anregung für alle gedacht, die sich damit beschäftigen und bereits ein wenig Erfahrung mit Freestyle im Solo und Paddeln allgemein im Tandem mitbringen. Uns selber dient es als Gedankenstütze und wir hoffen, dass es diese Funktion auch für andere erfüllen kann. Das Ganze ist im moment ein sehr lebendiges Dokument, wo sich jedes Mal, wenn wir zusammen auf dem Wasser waren noch Dinge ändern und neue Gedanken ergeben.


# Erläuterungen zum Dokument {.unnumbered}

Viele der Details im Tandem sind sehr abhängig vom Tandempaar (Paddelstil, Trim) und Boot. Wir haben uns bemüht, sowohl die Grundlagen, die allgemein (scheinbar) gelten, als auch Ideen und Anregungen zu eben solchen Details zu sammeln. Die feinere Abstimmung erfordert aber einfach Übung und Ausprobieren.

## Darstellung

::: {.column-margin .panel-tabset group="side"}
### Onside = Rechts {.unnumbered}
Bug paddelt rechts

### Onside = Links {.unnumbered}
Bug paddelt links
:::

Die Onside (Paddelseite) wird durch die Paddelseite des/der Bugpaddler*in bestimmt. 
[Für die Skizzen zu den Manövern kannst du rechts die Onside auswählen. Leider habe ich es noch nicht geschafft, dass die Auswahl sich auf die nächste Seite überträgt.]{.content-visible when-format="html"}

Bei einigen Manövern gibt es verschiedene Alternativen, was gemacht werden kann. Diese sind in der Tabelle als Aufzählung gelistest. 

In den Skizzen wird auf der linken Seite die Drehrichtung und Paddelstellung für die Placements gezeigt. Auf der rechten Seite ist die Kantung (Blick von hinten auf's Boot) im Verhältnis zum Paddel gezeigt.

## Struktur

Nach einigen einleitenden Erklärungen zu Begriffe, beginnen wir mit den Dingen, die wir als allgemeingültig empfinden. Danach folgt eine Darstellung der Manöver nach Quadranten sortiert gefolgt von einigen Spezialfällen wie Sideslips oder Gimbals. Ganz zum Schluss folgen dann noch einige Gedanken, welche Gedanken man sich machen kann, um sich nonverbale Kommunikation und Paddeln zu Musik zu erarbeiten.

[Texte und Bilder können unter [Create Commons Namensnennung 4.0 International](https://creativecommons.org/licenses/by/4.0/deed.de) genutzt werden.]{.content-visible when-format="pdf"}
